spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/project01
    username: sa
    password:
    dirver class name: org.h2.Driver

  jpa:
    hibernate:
      ddl auto: create
    properties:
      hibernate:
      show_sql : true #콘솔에 출력한다 이후 지워줄것
      format_sql : true

logging:
  level:
    org.hibernate.SQL : debug #debug 로그를 통해 본다